@extends('layouts.public')
@section('title', 'About Us | Makindye Ssabagabo Municipal Council')
@section('content')
<div class="about-page"><section class="about-hero"><div class="about-hero__overlay"></div><div class="about-hero__content"><span class="about-hero__crumb">Home / About Us</span><h1>{{ $settings->hero_title ?? 'About Makindye Ssabagabo Municipal Council' }}</h1></div></section><div class="about-container">
<section class="about-block card-shell about-intro"><div><span class="section-tag">Who we are</span><h2>History &amp; Background</h2>@foreach(preg_split('/\n\s*\n/', $settings->history_intro ?? '') as $paragraph)<p>{{ $paragraph }}</p>@endforeach</div><div class="about-facts">@foreach($settings->quick_facts ?? [] as $fact)<div class="about-fact"><span class="about-fact__value">{{ $fact['value'] ?? '' }}</span><span class="about-fact__label">{{ $fact['label'] ?? '' }}</span></div>@endforeach</div></section>
<section class="about-pillars">@foreach($settings->pillars ?? [] as $pillar)<div class="pillar-card"><div class="pillar-card__head"><div class="pillar-card__icon">◆</div><span class="pillar-card__tag">{{ $pillar['tag'] ?? '' }}</span></div><p>{{ $pillar['text'] ?? '' }}</p></div>@endforeach</section>
<section class="about-block card-shell"><span class="section-tag">Our mandate</span><h2>What We’re Here To Do</h2><p>{{ $settings->mandate_intro }}</p><h3 class="about-subhead">Our Mandate Is Our Promise</h3><p>{{ $settings->mandate_promise }}</p><ul class="about-list">@foreach($settings->mandate_functions ?? [] as $item)<li>{{ $item }}</li>@endforeach</ul></section>
<section class="about-block card-shell"><span class="section-tag">Where we're focused</span><h2>Functions &amp; Priority Focus Areas</h2><p>{{ $settings->priority_areas_intro }}</p><div class="about-priority-grid">@foreach($priorityAreas as $area)<div class="priority-card"><div class="priority-card__image"><img src="{{ $media($area->image) }}" alt=""></div><h3>{{ $area->title }}</h3><p>{{ $area->description }}</p></div>@endforeach</div></section>
<section class="about-block card-shell"><span class="section-tag">Leadership</span><h2>Administrative &amp; Council Leadership</h2><p>{{ $settings->leadership_intro }}</p><div class="about-leaders">@foreach($leaders as $leader)<div class="leader-card"><div class="leader-card__avatar">@if($leader->photo)<img src="{{ $media($leader->photo) }}" alt="{{ $leader->name }}">@else<span>◎</span>@endif</div><h3>{{ $leader->name }}</h3><span>{{ $leader->title }}</span></div>@endforeach</div></section>
</div></div>
@endsection
