@extends('layouts.public')
@section('title', 'Contact Us | Makindye Ssabagabo Municipal Council')
@section('content')
@php
    $addressLines = preg_split('/\r?\n/', $settings->address ?? "Makindye Ssabagabo Municipal Council\nP.O Box 1872, Kampala, Uganda\nNdejje Zanta");
    $phones = $settings->phones ?? [];
    $emails = $settings->emails ?? [];
    $socials = $settings->socials ?? [];
    $generalEmail = $emails[0]['email'] ?? 'info@msabagabo.go.ug';
@endphp
<div class="about-page"><section class="about-hero contact-hero"><div class="about-hero__overlay"></div><div class="about-hero__content"><span class="about-hero__crumb">Home / Contact</span><h1>Contact Us</h1></div></section><div class="about-container">
<section class="contact-grid"><div class="contact-info card-shell"><span class="section-tag">Get in touch</span><h2>Connect With Us</h2><p class="contact-info__lead">Connect with us for any inquiries, feedback, or support through our helplines.</p><div class="contact-info__block"><span class="contact-info__icon">⌖</span><div><h3>Head Office</h3><p>@foreach($addressLines as $line){{ $line }}<br>@endforeach</p></div></div><div class="contact-info__block"><span class="contact-info__icon">✉</span><div><h3>Email Us</h3>@foreach($emails as $email)<p><a href="mailto:{{ $email['email'] ?? '' }}">{{ $email['email'] ?? '' }}</a></p>@endforeach</div></div><div class="contact-info__block"><span class="contact-info__icon">☎</span><div><h3>Call</h3>@foreach($phones as $phone)<p>({{ $phone['label'] ?? 'Phone' }}): <a href="tel:{{ preg_replace('/\s+/', '', $phone['number'] ?? '') }}">{{ $phone['number'] ?? '' }}</a></p>@endforeach</div></div><div class="contact-info__socials"><h3>Follow our social media</h3><div class="contact-info__social-icons">@foreach($socials as $social)<a href="{{ $social['href'] ?? '#' }}" target="_blank" rel="noreferrer" aria-label="{{ $social['label'] ?? 'Social media' }}">●</a>@endforeach</div></div></div>
<form class="contact-form card-shell" onsubmit="event.preventDefault(); const body='Name: '+encodeURIComponent(this.name.value)+'%0AEmail: '+encodeURIComponent(this.email.value)+'%0APhone: '+encodeURIComponent(this.phone.value || 'N/A')+'%0A%0A'+encodeURIComponent(this.message.value); window.location.href='mailto:{{ $generalEmail }}?subject='+encodeURIComponent(this.subject.value)+'&body='+body;"><label>Full Name *<input type="text" name="name" required></label><label>Email address *<input type="email" name="email" required></label><label>Phone Number<input type="tel" name="phone"></label><label>Subject *<input type="text" name="subject" required></label><label>Your inquiry *<textarea name="message" required rows="5"></textarea></label><button type="submit" class="contact-form__submit">Submit →</button></form></section>
<section class="about-block card-shell contact-map"><div class="contact-map__header"><span class="section-tag">Find us</span><h2>Our Location</h2><a href="{{ $settings->directions_url ?? 'https://maps.app.goo.gl/8tFGDjcqJw99XzFy8' }}" target="_blank" rel="noreferrer" class="contact-map__link">Get Directions →</a></div><div class="contact-map__frame"><iframe title="Makindye Ssabagabo Municipal Council location" src="{{ $settings->map_embed_url ?? 'https://www.google.com/maps?q=Makindye+Ssabagabo+Municipal+Council,+Ndejje,+Uganda&output=embed' }}" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div></section>
</div></div>
@endsection
