@extends('layouts.public')
@section('title', 'Gallery | Makindye Ssabagabo Municipal Council')
@section('content')
<div class="gallery-page"><section class="gallery-hero" @if($images->first()) style="background-image:url('{{ $media($images->first()->image) }}')" @endif><div class="gallery-hero__overlay"></div><div class="gallery-hero__content"><span class="gallery-hero__crumb">Home / News &amp; Events / Gallery</span><h1>Gallery</h1></div></section><div class="gallery-container"><section class="gallery-filters"><button class="gallery-filter active" data-gallery-filter="all">All</button><button class="gallery-filter" data-gallery-filter="works">Infrastructure &amp; Site Works</button><button class="gallery-filter" data-gallery-filter="governance">Grievance Redress &amp; Community</button><button class="gallery-filter" data-gallery-filter="partners">Partner &amp; Program Visits</button></section><section class="gallery-grid">@foreach($images as $image)<button type="button" class="gallery-item" data-gallery-category="{{ $image->category }}" data-gallery-src="{{ $media($image->image) }}"><img src="{{ $media($image->image) }}" alt="{{ $image->title ?? 'Municipal Council gallery photo' }}"><span class="gallery-item__zoom">⌕</span></button>@endforeach</section><section class="gallery-partners card-shell"><span class="section-tag">Working together</span><h2>Development Partners</h2><p>Organizations that partner with Makindye Ssabagabo Municipal Council to fund and deliver services, infrastructure, and institutional strengthening for residents.</p><div class="gallery-partners__grid">@foreach($partners as $partner)<div class="gallery-partner"><img src="{{ $media($partner->icon) }}" alt="{{ $partner->name }}"><span>{{ $partner->name }}</span></div>@endforeach</div></section></div></div>
@endsection
@push('scripts')
<script>
document.querySelectorAll('[data-gallery-filter]').forEach((button) => button.addEventListener('click', () => { const key = button.dataset.galleryFilter; document.querySelectorAll('[data-gallery-filter]').forEach((b) => b.classList.toggle('active', b === button)); document.querySelectorAll('.gallery-item').forEach((item) => item.hidden = key !== 'all' && item.dataset.galleryCategory !== key); }));
document.querySelectorAll('.gallery-item').forEach((item) => item.addEventListener('click', () => { const box = document.createElement('div'); box.className = 'gallery-lightbox'; box.innerHTML = `<div class="gallery-lightbox__content"><button class="gallery-lightbox__close" aria-label="Close">×</button><img src="${item.dataset.gallerySrc}" alt="${item.querySelector('img').alt}"></div>`; box.addEventListener('click', () => box.remove()); box.querySelector('img').addEventListener('click', (e) => e.stopPropagation()); document.body.appendChild(box); }));
</script>
@endpush
