@extends('layouts.public')
@section('title', 'Programs | Makindye Ssabagabo Municipal Council')
@section('content')
<div class="progs-page"><section class="progs-hero"><div class="progs-hero__overlay"></div><div class="progs-hero__content"><span class="progs-hero__crumb">Home / Programs</span><h1>Programs that move Ssabagabo forward.</h1><p>Explore the work creating opportunity, better services, and stronger communities.</p></div></section><div class="progs-container"><section class="progs-stats">@foreach($stats as $stat)<div class="progs-stat"><span class="progs-stat__value">{{ $stat->value }}</span><span class="progs-stat__label">{{ $stat->label }}</span></div>@endforeach</section><section class="progs-filters"><button class="progs-filter active" data-program-filter="all">All</button>@foreach(['infrastructure' => 'Infrastructure', 'economic' => 'Economic Empowerment', 'education' => 'Education', 'protection' => 'Social Protection', 'governance' => 'Governance & Voice'] as $key => $label)<button class="progs-filter" data-program-filter="{{ $key }}">{{ $label }}</button>@endforeach</section><section class="progs-grid">@forelse($programs as $program)<article class="progs-card" data-program-theme="{{ $program->theme ?? '' }}"><div class="progs-card__image"><img src="{{ $media($program->image) ?? asset('gallery/event-12.jpg') }}" alt="{{ $program->name }} programme"></div><div class="progs-card__body"><h2>{{ $program->acronym }}</h2><span class="progs-card__name">{{ $program->name }}</span><p class="progs-card__tagline">{{ $program->tagline }}</p><span class="progs-card__fact">{{ $program->fact }}</span><button type="button" class="progs-card__more" data-program-open="{{ $program->acronym }}">Read more →</button></div><template id="program-{{ \Illuminate\Support\Str::slug($program->acronym) }}"><div><span class="progs-detail__fact">{{ $program->fact }}</span><h2>{{ $program->acronym }}</h2><span class="progs-detail__name">{{ $program->name }}</span><p>{{ $program->tagline }}</p>{!! nl2br(e($program->description)) !!}</div></template></article>@empty<p class="progs-state">No programs are available yet.</p>@endforelse</section></div></div>
@endsection
@push('scripts')
<script>
document.querySelectorAll('[data-program-filter]').forEach((button) => button.addEventListener('click', () => { const key = button.dataset.programFilter; document.querySelectorAll('[data-program-filter]').forEach((b) => b.classList.toggle('active', b === button)); document.querySelectorAll('.progs-card').forEach((card) => card.hidden = key !== 'all' && card.dataset.programTheme !== key); }));
document.querySelectorAll('[data-program-open]').forEach((button) => button.addEventListener('click', () => { const card = button.closest('.progs-card'); const source = card.querySelector('template').content.cloneNode(true); const box = document.createElement('div'); box.className = 'progs-detail'; const panel = document.createElement('div'); panel.className = 'progs-detail__panel'; panel.appendChild(source); box.appendChild(panel); box.addEventListener('click', () => box.remove()); panel.addEventListener('click', (e) => e.stopPropagation()); document.body.appendChild(box); }));
</script>
@endpush
